pipeline {
  agent {
    docker {
      dir './03-cicd-jenkins/jenkins-resources/calculator'
      image 'gradle'
    }

  stages {
  
   stage('Checkout code') {
      steps {
        echo "Checking out project"
        // GIT checkout
        checkout scm: [
                $class: 'GitSCM',
                branches: [[name: '*/main']], 
                doGenerateSubmoduleConfigurations: false, 
                extensions: [[$class: 'CleanCheckout']], 
                submoduleCfg: [], 
                userRemoteConfigs: [[url: 'https://github.com/monicacrespo/bootcamp-devops-student.git']]
        ]
      }
    }
    stage('Compile') {
      steps {
          dir('./03-cicd-jenkins/jenkins-resources/calculator'){
            echo "Compiling project"
            sh '''
            chmod +x gradlew
            ./gradlew compileJava
            '''
          }
      }
    }
    stage('Unit Tests') {
      steps {
        dir('./03-cicd-jenkins/jenkins-resources/calculator'){
          echo "Running unit tests" 
          sh './gradlew test'
        }
      }
    }
  }
}