Vagrant.configure("2") do |config|   
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.network "private_network", ip: "192.168.50.4"
    config.vm.provision "docker" 
    config.vm.boot_timeout = 500
end