pipeline {
  agent any

  stages {
	
   stage('Checkout code') {
      steps {
        echo "Checking out project"
      }
    }
    stage('Compile') {
      steps {
          dir('./03-cicd-jenkins/jenkins-resources/calculator'){
            echo "Compiling project"
            sh '''
            chmod +x gradlew
            ./gradlew compileJava
            '''
          }
      }
    }
    stage('Unit Tests') {
      steps {
        echo "Running unit tests"       
      }
    }   
  }
}